import {
  Plus, FolderOpen, MessageSquare, X, ToggleLeft, Settings,
  BookOpen, FileText, Keyboard, Square, Shield, Columns, Radio,
  Search, Copy, Download, Layout, LayoutGrid, History, Inbox, ListChecks,
  Kanban, GitBranch, GitCompareArrows, Crown, StickyNote, User, RotateCcw, Globe, Package,
  FlaskConical, Zap, Volume2, MessageSquareQuote, ListOrdered, Server, Sparkles,
  Brain, MessagesSquare, ExternalLink, BookOpenCheck, Key, Telescope
} from 'lucide-react'

export const ACTIONS = [
  { id: 'new-session', label: 'New Session', icon: Plus, section: 'Sessions', shortcut: '⌘N' },
  { id: 'close-tab', label: 'Close Tab', icon: X, section: 'Sessions', shortcut: '⌘W' },
  { id: 'stop-session', label: 'Stop Session', icon: Square, section: 'Sessions', shortcut: '⌘.' },
  { id: 'restart-session', label: 'Restart Session', icon: RotateCcw, section: 'Sessions' },
  { id: 'mission-control', label: 'Mission Control', icon: LayoutGrid, section: 'View', shortcut: '⌘M' },
  { id: 'inbox', label: 'Inbox', icon: Inbox, section: 'View', shortcut: '⌘I' },
  { id: 'plan-viewer', label: 'View Plan', icon: ListChecks, section: 'View' },
  { id: 'toggle-sidebar', label: 'Toggle Sidebar', icon: ToggleLeft, section: 'View', shortcut: '⌘\\' },
  { id: 'split-view', label: 'Split View', icon: Columns, section: 'View', shortcut: '⌘D' },
  { id: 'add-workspace', label: 'Add Workspace', icon: FolderOpen, section: 'Workspaces' },
  { id: 'workspace-settings', label: 'Workspace Settings', icon: Settings, section: 'Workspaces' },
  { id: 'prompt-library', label: 'Prompt Library', icon: BookOpen, section: 'Prompts', shortcut: '⌘/' },
  { id: 'new-prompt', label: 'New Prompt', icon: FileText, section: 'Prompts' },
  { id: 'guidelines', label: 'Guidelines', icon: Shield, section: 'Config', shortcut: '⌘G' },
  { id: 'mcp-servers', label: 'MCP Servers', icon: Server, section: 'Config', shortcut: '⌘⇧S' },
  { id: 'broadcast', label: 'Broadcast to Sessions', icon: Radio, section: 'Sessions', shortcut: '⌘⇧↵' },
  { id: 'clone-session', label: 'Clone Session', icon: Copy, section: 'Sessions' },
  { id: 'export-session', label: 'Export as Markdown', icon: Download, section: 'Sessions' },
  { id: 'distill-session', label: 'Distill Session', icon: Sparkles, section: 'Sessions' },
  { id: 'search', label: 'Search All Sessions', icon: Search, section: 'Search', shortcut: '⌘F' },
  { id: 'import-history', label: 'Import Claude Sessions', icon: History, section: 'History' },
  { id: 'feature-board', label: 'Feature Board', icon: Kanban, section: 'Orchestration', shortcut: '⌘B' },
  { id: 'pipeline-editor', label: 'Pipeline Editor', icon: GitCompareArrows, section: 'Orchestration', shortcut: '⌘⇧L' },
  { id: 'quick-feature', label: 'Quick Feature', icon: Zap, section: 'Orchestration', shortcut: '⌘⇧N' },
  { id: 'observatory', label: 'Research Hub — Feed', icon: Telescope, section: 'Research', shortcut: '⌘⇧O' },
  { id: 'agent-tree', label: 'Agent Tree', icon: GitBranch, section: 'Orchestration', shortcut: '⌘T' },
  { id: 'start-commander', label: 'Start Commander', icon: Crown, section: 'Orchestration' },
  { id: 'start-documentor', label: 'Start Documentor', icon: BookOpenCheck, section: 'Orchestration' },
  { id: 'docs-panel', label: 'Documentation Dashboard', icon: BookOpenCheck, section: 'Orchestration' },
  { id: 'save-template', label: 'Save as Template', icon: Layout, section: 'Templates' },
  { id: 'scratchpad', label: 'Scratchpad', icon: StickyNote, section: 'View', shortcut: '⌘J' },
  { id: 'manage-templates', label: 'Manage Templates', icon: Layout, section: 'Templates' },
  { id: 'grid-layout-editor', label: 'Edit Grid Layout', icon: LayoutGrid, section: 'View', gridOnly: true },
  { id: 'accounts', label: 'Manage Accounts', icon: User, section: 'Auth' },
  { id: 'config-viewer', label: 'Config Files & Tool Permissions', icon: Shield, section: 'Config' },
  { id: 'research', label: 'Research Hub — Library', icon: BookOpen, section: 'Research', shortcut: '⌘R' },
  { id: 'marketplace', label: 'Plugins & Skills', icon: Package, section: 'Config', shortcut: '⌘⇧M' },
  { id: 'quick-actions', label: 'Quick Action Palette', icon: Zap, section: 'Navigation', shortcut: '⌘Y' },
  { id: 'skills-library', label: 'Agent Skills Library', icon: Zap, section: 'Config', shortcut: '⌘O' },
  { id: 'experimental', label: 'Experimental Features', icon: FlaskConical, section: 'Config' },
  { id: 'safety', label: 'Safety Gate', icon: Shield, section: 'Config' },
  { id: 'cascades', label: 'Prompt Cascades', icon: ListOrdered, section: 'Prompts' },
  { id: 'general-settings', label: 'General Settings', icon: ToggleLeft, section: 'Config' },
  { id: 'sound-settings', label: 'Sound Notifications', icon: Volume2, section: 'Config' },
  { id: 'api-keys', label: 'API Keys', icon: Key, section: 'Config' },
  { id: 'code-review', label: 'Code Review', icon: GitCompareArrows, section: 'Git', shortcut: '⌘⇧G' },
  { id: 'annotate', label: 'Annotate Output', icon: MessageSquareQuote, section: 'Sessions', shortcut: '⌘⇧A' },
  { id: 'memory-search', label: 'Memory Search', icon: Brain, section: 'W2W' },
  { id: 'knowledge', label: 'Workspace Knowledge', icon: BookOpen, section: 'W2W' },
  { id: 'peer-messages', label: 'Peer Messages', icon: MessagesSquare, section: 'W2W' },
  { id: 'pop-out-terminal', label: 'Pop Out Terminal', icon: ExternalLink, section: 'Sessions', hint: 'Open in native OS terminal' },
  { id: 'shortcuts', label: 'Keyboard Shortcuts', icon: Keyboard, section: 'Help' },
]
